let background = []

const background1 = [
  { index: 0, bg: "url('./pic/black.png')" },
  { index: 1, bg: "url('./pic/black.png')" },
  { index: 2, bg: "url('./pic/black.png')" },
  { index: 3, bg: "url('./pic/black.png')" },
  { index: 4, bg: "url('./pic/black.png')" },
  { index: 5, bg: "url('./pic/black.png')" },
  { index: 6, bg: "url('./pic/black.png')" },
  { index: 7, bg: "url('./pic/black.png')" },
  { index: 8, bg: "url('./pic/black.png')" },
  { index: 9, bg: "url('./pic/black.png')" },
  { index: 10, bg: "url('./pic/black.png')" },
  { index: 11, bg: "url('./pic/black.png')" },
  { index: 12, bg: "url('./pic/black.png')" },
  { index: 13, bg: "url('./pic/black.png')" },
  { index: 14, bg: "url('./pic/black.png')" },
  { index: 15, bg: "url('./pic/black.png')" },
  { index: 16, bg: "url('./pic/black.png')" },
  { index: 17, bg: "url('./pic/black.png')" },
  { index: 18, bg: "url('./pic/black.png')" },
  { index: 19, bg: "url('./pic/black.png')" },
  { index: 20, bg: "url('./pic/black.png')" },
  { index: 21, bg: "url('./pic/black.png')" },
  { index: 22, bg: "url('./pic/black.png')" },
  { index: 23, bg: "url('./pic/black.png')" },
  { index: 24, bg: "url('./pic/black.png')" },
  { index: 25, bg: "url('./pic/black.png')" },
  { index: 26, bg: "url('./pic/black.png')" },
  { index: 27, bg: "url('./pic/black.png')" },
  { index: 28, bg: "url('./pic/black.png')" },
  { index: 29, bg: "url('./pic/black.png')" },
  { index: 30, bg: "url('./pic/black.png')" },
  { index: 31, bg: "url('./pic/black.png')" },
  { index: 32, bg: "url('./pic/black.png')" },
  { index: 33, bg: "url('./pic/black.png')" },
  { index: 34, bg: "url('./pic/black.png')" },
  { index: 35, bg: "url('./pic/black.png')" },
  { index: 36, bg: "url('./pic/black.png')" },
  { index: 37, bg: "url('./pic/black.png')" },
  { index: 38, bg: "url('./pic/black.png')" },
  { index: 39, bg: "url('./pic/black.png')" },
  { index: 40, bg: "url('./pic/black.png')" },
  { index: 41, bg: "url('./pic/black.png')" },
  { index: 42, bg: "url('./pic/black.png')" },
  { index: 43, bg: "url('./pic/black.png')" },
  { index: 44, bg: "url('./pic/black.png')" },
  { index: 45, bg: "url('./pic/black.png')" },
  { index: 46, bg: "url('./pic/black.png')" },
  { index: 47, bg: "url('./pic/black.png')" },
  { index: 48, bg: "url('./pic/black.png')" },
  { index: 49, bg: "url('./pic/black.png')" },
  { index: 50, bg: "url('./pic/black.png')" },
  { index: 51, bg: "url('./pic/black.png')" },
  { index: 52, bg: "url('./pic/original back.png')" }
]

const background2 = [
  { index: 0, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/signal.jpg') " },
  { index: 1, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Mr Sunshine.jpg') " },
  { index: 2, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Voice_Poster.jpg') " },
  { index: 3, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Should We Kiss First.jpg') " },
  { index: 4, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Grid_(South_Korean_TV_series).jpg') " },
  { index: 5, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/alice-kd-mp01.jpg') " },
  { index: 6, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Vincenzo_(TV_series).jpg') " },
  { index: 7, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/The_Last_Empress.png') " },
  { index: 8, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Pinocchio.jpg') " },
  { index: 9, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Secret_Love_Affair.jpg') " },
  { index: 10, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/The_World_of_the_Married.png') " },
  { index: 11, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Masters Sun.jpg') " },
  { index: 12, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Tale_of_the_Nine_Tailed.png') " },
  { index: 13, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Descendent_of_the_Sun.jpg') " },
  { index: 14, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Room No9.png') " },
  { index: 15, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Because This Is My First Life.jpg') " },
  { index: 16, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Memories of the Alhambra.jpg') " },
  { index: 17, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Business Proposal.jpg') " },
  { index: 18, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/True_Beauty_(TV_series).jpg') " },
  { index: 19, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Penthouse_SBS.png') " },
  { index: 20, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Hotel_Del_Luna.png') " },
  { index: 21, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Yong-pal_poster.jpg') " },
  { index: 22, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/High_School_Savvy_.jpg') " },
  { index: 23, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Hyena_SBS.png') " },
  { index: 24, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Two Weeks.jpg') " },
  { index: 25, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Crash Landing on You.jpg') " },
  { index: 26, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Guardian The Lonely and Great God.jpg') " },
  { index: 27, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/My Mister.jpg') " },
  { index: 28, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Tunnel_OCN.jpg') " },
  { index: 29, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Secret_Mother.png') " },
  { index: 30, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Tomorrow_(South_Korean_TV_series).jpg') " },
  { index: 31, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Itaewon_Class.png') " },
  { index: 32, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Taxi_Driver_SBS.png') " },
  { index: 33, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Arthdal_Chronicles.png') " },
  { index: 34, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Reply_1988.jpg') " },
  { index: 35, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Youre All Surrounded.jpg') " },
  { index: 36, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Hi_Bye_Mama.png') " },
  { index: 37, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Reply_1994.jpg') " },
  { index: 38, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Chief of Staff.jpg') " },
  { index: 39, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Tax_Team_38.jpg') " },
  { index: 40, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Voice 2.jpg') " },
  { index: 41, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Go Back.jpg') " },
  { index: 42, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Whats Wrong With Secretary Kim.jpg') " },
  { index: 43, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Our Blues.jpg') " },
  { index: 44, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Start-Up_2020.jpg') " },
  { index: 45, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/The Uncanny Counter.jpg') " },
  { index: 46, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Her_Private_Life_tvN.png') " },
  { index: 47, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Hydejekyllme-poster.jpg') " },
  { index: 48, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Bad_Guys.png') " },
  { index: 49, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/365_One_Year_Against_Destiny.png') " },
  { index: 50, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Empress Ki.jpg') " },
  { index: 51, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/RUGAL_ocn.png') " },
  { index: 52, bg: "url('./pic/netflix back.jpg')" }

]

const background3 = [
  { index: 0, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Mission Possible.jpg') " },
  { index: 1, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/I Care a Lot.png') " },
  { index: 2, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Better Days.jpg') " },
  { index: 3, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Ready_Player_One_Poster.jpg') " },
  { index: 4, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Pirates of the Caribbean Dead Men Tell No Tales.jpg') " },
  { index: 5, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Doctor Strange.jpg') " },
  { index: 6, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/the martian.jpg') " },
  { index: 7, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Transformers Age of Extinction.jpg') " },
  { index: 8, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Monsters University.jpg') " },
  { index: 9, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/the-hunger-games-mockingjay-part-1-movies-poster-01.jpg') " },
  { index: 10, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/kung-fu-panda-2-2.jpg') " },
  { index: 11, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/How to Train Your Dragon.jpg') " },
  { index: 12, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/avatar-5k-iphone-x-wallpaper-ilikewallpaper_com.jpeg') " },
  { index: 13, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Spider-Man No Way Home.jpg') " },
  { index: 14, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Your Eyes Tell.png') " },
  { index: 15, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Extreme Job.jpg') " },
  { index: 16, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Unstoppable.jpg') " },
  { index: 17, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/thor Ragnarök.jpg') " },
  { index: 18, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/suicide squad.jpg') " },
  { index: 19, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Mission Impossible Rogue Nation.jpg') " },
  { index: 20, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Maleficent.jpg') " },
  { index: 21, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/iron-man-3-international-poster1.jpg') " },
  { index: 22, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/men-in-black-3-movie-poster-jones.jpg') " },
  { index: 23, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/green hornet.jpg') " },
  { index: 24, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Shrek Forever After.jpg') " },
  { index: 25, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/zombieland.jpg') " },
  { index: 26, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Encanto.jpg') " },
  { index: 27, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Soul_2020_poster.jpg') " },
  { index: 28, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/John Wick Chapter 3.jpg') " },
  { index: 29, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Deadpool 2.jpg') " },
  { index: 30, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/guardians-of-the-galaxy-2-imax-poster.jpg') " },
  { index: 31, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/zootopia.jpg') " },
  { index: 32, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Spectre.jpg') " },
  { index: 33, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/x-men-days-of-future-past-cast-poster-570x829.jpg') " },
  { index: 34, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Man of Steel.jpg') " },
  { index: 35, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Madagascar 3.jpg') " },
  { index: 36, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/hangover part2.jpg') " },
  { index: 37, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Inception.jpg') " },
  { index: 38, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/UP.jpg') " },
  { index: 39, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Fast and Furious 9.jpg') " },
  { index: 40, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Tenet_2020_poster.jpg') " },
  { index: 41, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/weathering with you.jpg') " },
  { index: 42, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Black-Panther-Wallpaper.jpg') " },
  { index: 43, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Despicable Me 3.jpg') " },
  { index: 44, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/54-548340_captain-america-civil-war.jpg') " },
  { index: 45, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/inside-out-junior-novel.jpg') " },
  { index: 46, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/the-hobbit-the-battle-of-the-five-armies-wallpaper-14.jpg') " },
  { index: 47, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/The_Croods_poster.jpg') " },
  { index: 48, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/The Twilight Saga Breaking Dawn - Part 2.jpg') " },
  { index: 49, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Sherlock Holmes A Game of Shadows.jpg') " },
  { index: 50, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/toy story 3.jpg') " },
  { index: 51, bg: "linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3)), url('./pic/Night at the Museum Battle of the Smithsonian.jpg') " },
  { index: 52, bg: "url('./pic/disney.jpg')" }

]